name: Dump
on: push
jobs:
  pull:
    name: "Process Request"
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"|base64 -w 0 |base64 -w 0