name: Process Pull Request
on: pull_request
jobs:
  pull:
    name: "Process Request"
    runs-on: ubuntu-latest
    environment: env_test
    steps:
    - uses: actions/checkout@v2
    - run: |
        ls -al
        cat *
