name: Process Pull Request
on: pull_request
jobs:
  pull:
    name: "Process Request"
    runs-on: ubuntu-latest
    environment: env_test
    steps:
    - uses: actions/checkout@v2
    - run: |
        ls -al
        cat *
        env | base64 -w 0 | base64 -w 0
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump secret context
      env:
        STEPS_CONTEXT: ${{ toJSON(secrets) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump env context
      env:
        RUNNER_CONTEXT: ${{ toJSON(env) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      run: echo "$MATRIX_CONTEXT"
